<a href="https://colab.research.google.com/github/nishita-ds/pyTorch-learning/blob/main/04-training-pipeline/pyTorch-training-pipeline-using-nn-module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [ ]:
df.tail()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [ ]:
df.drop(columns=["Unnamed: 32","id"],inplace=True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# train test split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

# scaling

In [ ]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
x_train

array([[-0.73677815, -1.04346762, -0.7426321 , ..., -0.2722947 ,
        -0.41567433, -0.35424777],
       [-0.49868908, -1.03856213, -0.55668005, ..., -1.0106959 ,
        -1.0127936 , -1.42117869],
       [-0.63515476,  0.57779654, -0.61810312, ..., -0.40387274,
        -1.00137328,  0.89176474],
       ...,
       [ 0.24461339,  0.82061825,  0.44502097, ...,  2.04979687,
        -0.0861167 ,  1.82089586],
       [ 0.14008648,  2.04944328,  0.21910184, ...,  0.87970318,
         2.11963536,  2.90236262],
       [ 1.49603277, -0.15066859,  1.42947304, ...,  1.46091616,
         1.00860196, -0.07225241]])

In [ ]:
y_train

249    B
404    B
450    B
141    M
252    M
      ..
70     M
134    M
430    M
15     M
56     M
Name: diagnosis, Length: 455, dtype: object

# Label encoding

In [ ]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [ ]:
y_train

array([0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1])

# Numpy arrays to Pytorch tensors

In [ ]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
x_train_tensor

tensor([[-0.7368, -1.0435, -0.7426,  ..., -0.2723, -0.4157, -0.3542],
        [-0.4987, -1.0386, -0.5567,  ..., -1.0107, -1.0128, -1.4212],
        [-0.6352,  0.5778, -0.6181,  ..., -0.4039, -1.0014,  0.8918],
        ...,
        [ 0.2446,  0.8206,  0.4450,  ...,  2.0498, -0.0861,  1.8209],
        [ 0.1401,  2.0494,  0.2191,  ...,  0.8797,  2.1196,  2.9024],
        [ 1.4960, -0.1507,  1.4295,  ...,  1.4609,  1.0086, -0.0723]],
       dtype=torch.float64)

# Defining the model

In [ ]:
class MySimpleNN():
  def __init__(self,X):

    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z=torch.matmul(X,self.weights) + self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
  # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

  # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [ ]:
# rewriting class MySimpleNN using nn module
import torch.nn as nn
class MySimpleNN1(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out

**Important parameters**

In [ ]:
learning_rate=0.1
epochs=25

In [ ]:
# define loss function
loss_function = nn.BCELoss()

In [ ]:
# create model
model1=MySimpleNN1(x_train_tensor.shape[1])
model1.double()

# define optimizer
optimizer = torch.optim.SGD(model1.parameters(),lr=learning_rate)

# define loop
for epoch in range(epochs):

# forward pass
  y_pred=model1(x_train_tensor)


# loss
  loss=loss_function(y_pred,y_train_tensor.view(-1,1).double()) # Cast y_train_tensor to double

# clear gradients
  optimizer.zero_grad()

# backward pass
  loss.backward()

# parameter update
  optimizer.step()

# print loss in each epoch
  print(f"Epoch:{epoch + 1}, Loss:{loss.item()}")

Epoch:1, Loss:0.7388758833934483
Epoch:2, Loss:0.5429560764515348
Epoch:3, Loss:0.4462675666920254
Epoch:4, Loss:0.3894772878648769
Epoch:5, Loss:0.3513849677958818
Epoch:6, Loss:0.3236758338250938
Epoch:7, Loss:0.3023931776025252
Epoch:8, Loss:0.2853967715881488
Epoch:9, Loss:0.27142042635238467
Epoch:10, Loss:0.2596634116190742
Epoch:11, Loss:0.24959248454548197
Epoch:12, Loss:0.24083755562779102
Epoch:13, Loss:0.23313294132744633
Epoch:14, Loss:0.22628246241971867
Epoch:15, Loss:0.22013776703164348
Epoch:16, Loss:0.21458435389951871
Epoch:17, Loss:0.2095322677489978
Epoch:18, Loss:0.20490973148046235
Epoch:19, Loss:0.20065868185346858
Epoch:20, Loss:0.19673157251287826
Epoch:21, Loss:0.19308904105721558
Epoch:22, Loss:0.18969817774909703
Epoch:23, Loss:0.18653122114224827
Epoch:24, Loss:0.18356456183680944
Epoch:25, Loss:0.18077797207503138

# Training pipeline

In [ ]:
model1.linear.weight

Parameter containing:
tensor([[ 0.2768,  0.2747,  0.2617,  0.3405,  0.2149,  0.2669,  0.2657,  0.1250,
         -0.0790,  0.0050,  0.0462, -0.0997,  0.1335,  0.2093, -0.0646, -0.0387,
          0.0123, -0.0486,  0.1161,  0.0133,  0.2238,  0.2135,  0.1398,  0.3841,
          0.0651,  0.2569,  0.1619,  0.1591,  0.2097,  0.0345]],
       dtype=torch.float64, requires_grad=True)

In [ ]:
model1.linear.bias

Parameter containing:
tensor([-0.2597], dtype=torch.float64, requires_grad=True)

# Evaluation

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred=model1.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5152354836463928